In [1]:
import numpy as np

In [2]:
a1 = np.array([-2, -1, 0, 1])

In [3]:
a2 = np.array([-1, 0, 1])

In [15]:
o1, o2 = np.meshgrid(a1, a2)
o3, o4 = np.meshgrid(a2, a1)
print("--- left ---")
print("a1_a2: \n", o1)
print("a2_a1: \n", o3)
print("--- right ---")
print("a1_a2: \n", o2)
print("a2_a1: \n", o4)

--- left ---
a1_a2: 
 [[-2 -1  0  1]
 [-2 -1  0  1]
 [-2 -1  0  1]]
a2_a1: 
 [[-1  0  1]
 [-1  0  1]
 [-1  0  1]
 [-1  0  1]]
--- right ---
a1_a2: 
 [[-1 -1 -1 -1]
 [ 0  0  0  0]
 [ 1  1  1  1]]
a2_a1: 
 [[-2 -2 -2]
 [-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]


In [43]:
import numpy as np

In [44]:
a=[[1],[2],[3]]
b=[[1],[2],[3]]
c=[[1],[2],[3]]
d=[[1],[2],[3]]

In [47]:
nh = np.hstack([a,b,c,d])
print(nh, nh.shape)

[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]] (3, 4)


In [48]:
nv = np.vstack([a,b,c,d])
print(nv, nv.shape)

[[1]
 [2]
 [3]
 [1]
 [2]
 [3]
 [1]
 [2]
 [3]
 [1]
 [2]
 [3]] (12, 1)


In [49]:
a = [[1, 2, 3]]
b = [[1, 2, 3]]
c = [[1, 2, 3]]
d = [[1, 2, 3]]

In [50]:
nv = np.vstack([a,b,c,d])
print(nv, nv.shape)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]] (4, 3)


In [51]:
nh = np.hstack([a,b,c,d])
print(nh, nh.shape)

[[1 2 3 1 2 3 1 2 3 1 2 3]] (1, 12)


In [52]:
n1 = np.stack([a,b,c,d])

print(n1, n1.shape)

[[[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]] (4, 1, 3)


In [53]:
n2 = np.stack([a,b,c,d], axis = 0)
print(n2, n2.shape)

[[[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]

 [[1 2 3]]] (4, 1, 3)


In [38]:
n3 = np.stack([a,b,c,d], axis = 1)
print(n3, n3.shape)
# axis决定的是前两个dimension增加哪一个

[[[1 2 3]
  [1 2 3]
  [1 2 3]
  [1 2 3]]] (1, 4, 3)
